# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rleC <- function(x) {
    .Call('_pnrShad_rleC', PACKAGE = 'pnrShad', x)
}

delayC <- function(x, damRkms) {
    .Call('_pnrShad_delayC', PACKAGE = 'pnrShad', x, damRkms)
}

entryC <- function(entry_prob, entryDate, x) {
    .Call('_pnrShad_entryC', PACKAGE = 'pnrShad', entry_prob, entryDate, x)
}

motivationPenaltyC <- function(eFFs, newTU, ppPenalty) {
    .Call('_pnrShad_motivationPenaltyC', PACKAGE = 'pnrShad', eFFs, newTU, ppPenalty)
}

moveC <- function(day, entryDate, dailyMove, maxR, eFFs, rkm1, rkm2, spawnDate) {
    .Call('_pnrShad_moveC', PACKAGE = 'pnrShad', day, entryDate, dailyMove, maxR, eFFs, rkm1, rkm2, spawnDate)
}

maxrkmC <- function(fishAges, maxrkm, upstream_path, routes) {
    .Call('_pnrShad_maxrkmC', PACKAGE = 'pnrShad', fishAges, maxrkm, upstream_path, routes)
}

fishPU <- function(puRkm, finalRKM, puNames) {
    .Call('_pnrShad_fishPU', PACKAGE = 'pnrShad', puRkm, finalRKM, puNames)
}

spawnDateC <- function(predTemps, spawnTemp, entryDate) {
    .Call('_pnrShad_spawnDateC', PACKAGE = 'pnrShad', predTemps, spawnTemp, entryDate)
}

upstreamPathC <- function(x) {
    .Call('_pnrShad_upstreamPathC', PACKAGE = 'pnrShad', x)
}

