# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

tempC <- function(days, years, coeffs) {
    .Call('_shadia_tempC', PACKAGE = 'shadia', days, years, coeffs)
}

rleC <- function(x) {
    .Call('_shadia_rleC', PACKAGE = 'shadia', x)
}

delayC <- function(x, damRkms) {
    .Call('_shadia_delayC', PACKAGE = 'shadia', x, damRkms)
}

entryC <- function(entry_prob, entryDate, x) {
    .Call('_shadia_entryC', PACKAGE = 'shadia', entry_prob, entryDate, x)
}

motivationPenaltyC <- function(eFFs, newTU, ppPenalty) {
    .Call('_shadia_motivationPenaltyC', PACKAGE = 'shadia', eFFs, newTU, ppPenalty)
}

moveC <- function(day, entryDate, dailyMove, maxR, eFFs, rkm1, rkm2, spawnDate) {
    .Call('_shadia_moveC', PACKAGE = 'shadia', day, entryDate, dailyMove, maxR, eFFs, rkm1, rkm2, spawnDate)
}

maxrkmC <- function(fishAges, maxrkm, upstream_path, routes) {
    .Call('_shadia_maxrkmC', PACKAGE = 'shadia', fishAges, maxrkm, upstream_path, routes)
}

fishPU <- function(puRkm, finalRKM, puNames) {
    .Call('_shadia_fishPU', PACKAGE = 'shadia', puRkm, finalRKM, puNames)
}

spawnDateC <- function(predTemps, spawnTemp, entryDate) {
    .Call('_shadia_spawnDateC', PACKAGE = 'shadia', predTemps, spawnTemp, entryDate)
}

upstreamPathC <- function(x) {
    .Call('_shadia_upstreamPathC', PACKAGE = 'shadia', x)
}

